'!TITLE "Robot program"
#Include "Variant.h"

#define TCP_HEADER_LENGTH		16

#define TCP_CMD_NODEADDRTOPLC	0
#define TCP_CMD_NODEADDRFROMPLC	1
#define TCP_CMD_FINSFRAME		2

#define FINS_HEADER_LENGTH		10
#define FINS_CMD_LENGTH			2
#define FINS_RE_CODE_LENGTH		2

#define CTRL_MODEL_LENGTH		20
#define CTRL_VERSION_LENGTH		20
#define SYS_RESERVED_LENGTH		40
#define AREA_DATA_LENGTH		12

#define FUNC_MEMORYAREA			&H01
#define FUNC_PARAMETERAREA		&H02
#define FUNC_PROGRAMAREA		&H03
#define FUNC_OPERATINGMODE		&H04
#define FUNC_MACHINECONFIG		&H05
#define FUNC_STATUS				&H06
#define FUNC_TIMEDATA			&H07
#define FUNC_MESSAGEDISPLAY		&H09
#define FUNC_ACCESSRIGHTS		&H0C
#define FUNC_ERRORLOG			&H21
#define FUNC_FINSWRITELOG		&H21
#define FUNC_FILEMEMORY			&H22
#define FUNC_DEBUGGING			&H23
#define FUNC_SERIALGATEWAY		&H28

#define MEMORYAREA_READ			&H01
#define MEMORYAREA_WRITE		&H02
#define MEMORYAREA_FILL			&H03
#define MEMORYAREA_MULTIREAD	&H04
#define MEMORYAREA_TRANSFER		&H05

#define MEMORYAREA_TYPE_DATAMEM	&H82
#define MEMORYAREA_TYPE_COMMIO	&HB0
#define MEMORYAREA_TYPE_WORK	&HB1
#define MEMORYAREA_TYPE_HOLD	&HB2
#define MEMORYAREA_TYPE_AUX		&HB3

#define PARAMETERAREA_READ		&H01
#define PARAMETERAREA_WRITE		&H02
#define PARAMETERAREA_FILL		&H03

#define PROGRAMAREA_READ		&H06
#define PROGRAMAREA_WRITE		&H07
#define PROGRAMAREA_FILL		&H08

#define OPERATINGMODE_RUN		&H01
#define OPERATINGMODE_STOP		&H02

#define MACHINECONFIG_READCPU	&H01
#define MACHINECONFIG_READCONN	&H02

#define BYTE_MAX_VALUE			255
#define BYTE_MIN_VALUE			0

#define PLCTYPE_NJ101			0
#define PLCTYPE_NJ301			1
#define PLCTYPE_NJ501			2
#define PLCTYPE_NX1P2			3
#define PLCTYPE_NX102			4
#define PLCTYPE_NX701			5
#define PLCTYPE_NY512			6
#define PLCTYPE_NY532			7
#define PLCTYPE_NJNXNYSeries	8
#define PLCTYPE_CJ2				9
#define PLCTYPE_CP1				10
#define PLCTYPE_CSeries			11
#define PLCTYPE_Unknown			12

Dim tcpClientLine As Integer = 8
Dim remoteNodeId As Integer = BYTE_MIN_VALUE
Dim localNodeId As Integer = BYTE_MIN_VALUE
Dim currRequestId As Integer = BYTE_MIN_VALUE
Dim plcType As Integer = PLCTYPE_Unknown
Dim plcVersion As Integer = 0
